### ISSUE TITLE
Exception: ERROR: No internet connection.

### ISSUE THREAD

**Issue by kazumaxneo** [michaelgruenstaeudl/airpg#1]
Hi.
When I run the airpg_identify.py command, I get the following error.

Traceback (most recent call last):
  File "/home/kazu/miniconda/bin/airpg_identify.py", line 151, in <module>
    main(args)
  File "/home/kazu/miniconda/bin/airpg_identify.py", line 102, in main
    raise Exception("ERROR: No internet connection.")
Exception: ERROR: No internet connection.

What is the cause?
I installed this package using pip in a python 3.9 environment.

**Comment by michaelgruenstaeudl** [comment]
Thanks for pointing this out. I have updated the repo to fix that bug.

**Comment by kazumaxneo** [comment]
Thanks you !
I upgraded from github, and It works.

**Comment by michaelgruenstaeudl** [comment]
Great to hear! Issue closed.
